version: '3.8'

services:

  db:
    build: 
       context: mysql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql_database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=joni
      - MYSQL_USER=joni
    networks:
      - node-network

  node: 
    build: 
      context: node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js 
    depends_on:
      - db
    networks:
     - node-network
    volumes:
     - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"

  nginx:
    restart: always
    build: 
      context: ./nginx
    container_name: nginx
    #entrypoint: dockerize -wait tcp://node:3000 -timeout 20s 
    depends_on:
      - node
    networks:
      - node-network
    ports:
    - "8080:80"  

networks:
  node-network:
    driver: bridge    